# Generated by Django 5.1.5 on 2025-01-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.PositiveIntegerField()),
                ('verified', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
                ('ref', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ['-fund_date'],
            },
        ),
    ]
