# Generated by Django 5.1.5 on 2025-01-21 19:34

import userauths.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=userauths.models.user_directory_path),
        ),
    ]
