# Generated by Django 5.1.5 on 2025-01-21 19:59

import django.core.files.storage
import django.utils.timezone
import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_file_productattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattachment',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productattachment',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productattachment',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productattachment',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='productattachment',
            name='book',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\USER\\Desktop\\nnekkie\\local-cdn\\protected'), upload_to=product.models.handlde_product_attachment_upload),
        ),
    ]
