# Generated by Django 5.1.5 on 2025-01-21 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_productattachment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='cover.jpg', upload_to='product/'),
        ),
    ]
