# Generated by Django 5.1.5 on 2025-01-27 12:00

import django.core.files.storage
import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattachment',
            name='book',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=product.models.handlde_product_attachment_upload),
        ),
    ]
