# Generated by Django 5.1.5 on 2025-01-27 18:10

import django.core.files.storage
import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_productattachment_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattachment',
            name='book',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\USER\\Desktop\\nnekkie\\local-cdn\\protected'), upload_to=product.models.handlde_product_attachment_upload),
        ),
    ]
