# Generated by Django 5.1.5 on 2025-01-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_productattachment_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattachment',
            name='desc',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
