# Generated by Django 5.1.5 on 2025-01-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_productattachment_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattachment',
            name='desc',
            field=models.CharField(default='No data represented here', max_length=30),
        ),
    ]
