# Generated by Django 5.1.5 on 2025-01-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_productattachment_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattachment',
            name='desc',
        ),
        migrations.AddField(
            model_name='productattachment',
            name='description',
            field=models.CharField(default='No data represented here', max_length=30),
        ),
    ]
