# Generated by Django 5.1.5 on 2025-01-28 19:30

import facebook_prj.storages.backends
import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_remove_productattachment_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattachment',
            name='book',
            field=models.FileField(blank=True, null=True, storage=facebook_prj.storages.backends.ProtectedStorage(), upload_to=product.models.handlde_product_attachment_upload),
        ),
    ]
