# Generated by Django 5.1.5 on 2025-01-25 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snaps',
            name='description',
        ),
        migrations.RemoveField(
            model_name='snaps',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='snaps',
            name='image',
        ),
        migrations.RemoveField(
            model_name='snaps',
            name='title',
        ),
    ]
