# Generated by Django 5.1.5 on 2025-01-25 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_snapviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='url',
        ),
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
    ]
